USE Proyecto1F1;


DROP TABLE IF EXISTS TrackTag;
DROP TABLE IF EXISTS AlbumTag;
DROP TABLE IF EXISTS ArtistTag;
DROP TABLE IF EXISTS TrackCopyright;
DROP TABLE IF EXISTS AlbumCopyright;
DROP TABLE IF EXISTS Copyright;
DROP TABLE IF EXISTS AlbumLabel;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS ArtistAlias;
DROP TABLE IF EXISTS TrackGenre;
DROP TABLE IF EXISTS ArtistGenre;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Track;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS Label;