-- Registro Usuario
CALL PR1('Diego Andres', 'Lopez Lopez', 'diand23@gmail.com', '1996-02-01', 'diloans', 6);
CALL PR1('Jose Pablo', 'Garcia Robles', 'pablojose@gmail.com', '2000-01-01', '@skartar.li', 5);
CALL PR1('Jose Alejandro', 'Gimenez Xin', 'josegim@gmail.com', '2000-01-03', 'xingi13@12', 10);
CALL PR1('Cesar Augusto', 'Hernandez Gomez', 'cegomez14@gmail.com', '2000-12-05', 'gonandez5412', 10);
CALL PR1('Jose Alejandro', 'Gimenez Xin', 'josegim@gmail.com', '2000-01-03', 'xingi13@12', 10);
CALL PR1('Jose Alejandro', 'Gimenez Xin', 'josegim@gmail.com', '2000-01-03', 'xingi13@12', 10);
CALL PR1('María Fernanda', 'Lopez Martínez', 'maria.fernanda@gmail.com', '1998-05-22', 'ferlopez98', 15);
CALL PR1('Carlos Alberto', 'Rodríguez Sánchez', 'carlos.rodriguez@hotmail.com', '1995-10-10', 'carlitossan123', 12);
CALL PR1('Ana Isabel', 'Gómez Torres', 'ana.gomez@yahoo.com', '1999-03-30', 'ani_gomez99', 8);
CALL PR1('Luis Eduardo', 'Pérez Ramírez', 'luis.perez@gmail.com', '2001-07-17', 'lucho_2001', 20)
CALL PR1('Elena Patricia', 'Vargas Ruiz', 'elena.vargas@hotmail.com', '2002-02-28', 'paty_vr28', 18);
CALL PR1('Gabriel Andrés', 'Martínez Flores', 'gabriel.martinez@gmail.com', '1997-09-15', 'gabi_andres97', 25);
CALL PR1('Lucía Alejandra', 'Hernández Ocampo', 'lucia.hernandez@yahoo.com', '2000-12-05', 'lucy_hernandez2000', 22);
CALL PR1('Jorge Ricardo', 'Mendoza Castro', 'jorge.mendoza@hotmail.com', '1994-11-20', 'jormencas94', 5);
CALL PR1('Sofía Natalia', 'Reyes Delgado', 'sofia.reyes@gmail.com', '2003-04-12', 'sofidelgado03', 30);
CALL PR1('Pedro Francisco', 'Ramírez López', 'pedro.ramirez@yahoo.com', '1996-08-08', 'pfr_96lopez', 14);
CALL PR1('Juan Carlos', 'Fernández Silva', 'juan.carlos@hotmail.com', '1992-06-14', 'juancf92', 16);
CALL PR1('Laura Beatriz', 'Sosa Martínez', 'laura.sosa@gmail.com', '1997-03-21', 'laurasm97', 11);
CALL PR1('Miguel Ángel', 'García Pérez', 'miguel.angel@yahoo.com', '2000-12-29', 'miguelgp00', 9);
CALL PR1('Valentina Andrea', 'Moreno Díaz', 'valentina.moreno@gmail.com', '2001-05-16', 'valen_diaz01', 13);
CALL PR1('Ricardo Javier', 'Ortiz Muñoz', 'ricardo.ortiz@hotmail.com', '1995-09-23', 'ricortiz95', 7);
CALL PR1('Paola Cristina', 'López Vargas', 'paola.lopez@yahoo.com', '1999-11-08', 'paolita99lv', 19);
CALL PR1('Diego Armando', 'Jiménez Santos', 'diego.jimenez@gmail.com', '2002-07-04', 'dieguito2002', 17);
CALL PR1('Camila Alejandra', 'Rojas Ramírez', 'camila.rojas@hotmail.com', '2003-01-19', 'cami_rojita03', 14);
CALL PR1('Oscar Eduardo', 'Ruiz García', 'oscar.ruiz@yahoo.com', '1998-04-11', 'oscarino98', 18);
CALL PR1('Patricia Elena', 'Cruz Herrera', 'patricia.cruz@gmail.com', '1996-02-27', 'pattycr96', 21);
CALL PR1('Felipe Antonio', 'Castro Rivas', 'felipe.castro@hotmail.com', '2000-10-05', 'felcastr00', 6);
CALL PR1('Daniel Esteban', 'Vega Morales', 'daniel.vega@gmail.com', '2001-06-23', 'danivmor01', 20);
CALL PR1('Karina Judith', 'Mendoza Ruiz', 'karina.mendoza@yahoo.com', '1997-12-31', 'karimr97', 24);
CALL PR1('Rodrigo Hernán', 'Pérez Jiménez', 'rodrigo.perez@hotmail.com', '1994-07-09', 'rodri_her94', 28);
CALL PR1('Florencia Isabel', 'Ortiz García', 'florencia.ortiz@gmail.com', '2003-11-03', 'flor_ort03', 26);
CALL PR1('Gustavo Raúl', 'Ramírez Sánchez', 'gustavo.ramirez@yahoo.com', '1995-08-15', 'gusram95', 22);
CALL PR1('Adriana Pilar', 'Díaz López', 'adriana.diaz@hotmail.com', '1998-03-18', 'adrilop98', 27);
CALL PR1('Mauricio José', 'Martínez Flores', 'mauricio.martinez@gmail.com', '1999-12-01', 'maumartflo99', 30);
CALL PR1('Jessica Alejandra', 'Vargas Muñoz', 'jessica.vargas@yahoo.com', '2000-09-25', 'jessivargmu00', 15);
CALL PR1('Héctor Manuel', 'Reyes Castillo', 'hector.reyes@hotmail.com', '2001-04-14', 'hecmanr00', 23);

-- Creacion Curso
CALL PR5('Fisica Basica', 11);
CALL PR5('Matematica Basica 1', 0);
CALL PR5('Matemáticas Avanzadas', 12);
CALL PR5('Química General', 13);
CALL PR5('Historia Universal', 14);
CALL PR5('Biología Molecular', 15);
CALL PR5('Filosofía Contemporánea', 16);
CALL PR5('Literatura Clásica', 17);
CALL PR5('Cálculo Diferencial', 18);
CALL PR5('Programación en C++', 19);
CALL PR5('Estadística Aplicada', 20);
CALL PR5('Geografía Física', 21);
CALL PR5('Economía Internacional', 22);
CALL PR5('Sociología de la Educación', 23);
CALL PR5('Análisis de Circuitos', 24);
CALL PR5('Ingeniería de Software', 25);
CALL PR5('Psicología del Desarrollo', 6);
CALL PR5('Microbiología', 9);
CALL PR5('Química Orgánica', 5);
CALL PR5('Redes de Computadoras', 29);
CALL PR5('Algebra Lineal', 15);
CALL PR5('Ética Profesional', 11);
CALL PR5('Derecho Constitucional', 32);
CALL PR5('Física Moderna', 10);
CALL PR5('Administración de Empresas', 34);
CALL PR5('Análisis de Datos', 35);
CALL PR5('Investigación de Mercados', 36);
CALL PR5('Electromagnetismo', 5);
CALL PR5('Historia del Arte', 0);
CALL PR5('Marketing Digital', 3);
CALL PR5('Contabilidad Financiera', 40);
CALL PR5('Arquitectura de Computadoras', 41);
CALL PR5('Cálculo Diferencial', 12);
CALL PR5('Álgebra Lineal', 15);
CALL PR5('Química General', 18);
CALL PR5('Física II', 14);
CALL PR5('Programación Avanzada', 20);
CALL PR5('Ingeniería de Software', 17);
CALL PR5('Matemáticas Discretas', 13);
CALL PR5('Electromagnetismo', 19);
CALL PR5('Termodinámica', 16);
CALL PR5('Estructuras de Datos', 21);
CALL PR5('Redes de Computadoras', 22);
CALL PR5('Bases de Datos', 25);
CALL PR5('Inteligencia Artificial', 24);
CALL PR5('Probabilidad y Estadística', 23);
CALL PR5('Mecánica de Fluidos', 26);
CALL PR5('Sistemas Operativos', 28);
CALL PR5('Diseño de Algoritmos', 29);
CALL PR5('Circuitos Eléctricos', 27);
CALL PR5('Optimización', 30);
CALL PR5('Seguridad Informática', 31);
CALL PR5('Control de Procesos', 32);
CALL PR5('Análisis Numérico', 33);
CALL PR5('Gestión de Proyectos', 35);
CALL PR5('Métodos Numéricos', 36);
CALL PR5('Ciencia de Materiales', 34);
CALL PR5('Robótica', 37);
CALL PR5('Análisis de Señales', 38);
CALL PR5('Computación Cuántica', 39);
CALL PR5('Desarrollo Web', 40);
CALL PR5('Sistemas Digitales', 41);

-- Rol Estudiante/Tutor
CALL PR4('Tutor');
CALL PR4('Estudiante');

-- Asignacion Curso
CALL PR3('john.doe@example.com', 4);
CALL PR3('josegim@gmail.com', 12);
CALL PR3('maria.fernanda@gmail.com', 15);
CALL PR3('carlos.rodriguez@hotmail.com', 18);
CALL PR3('ana.gomez@yahoo.com', 14);
CALL PR3('luis.perez@gmail.com', 20);
CALL PR3('elena.vargas@hotmail.com', 21);
CALL PR3('gabriel.martinez@gmail.com', 19);
CALL PR3('lucia.hernandez@yahoo.com', 17);
CALL PR3('jorge.mendoza@hotmail.com', 13);
CALL PR3('sofia.reyes@gmail.com', 16);
CALL PR3('pedro.ramirez@yahoo.com', 25);
CALL PR3('juan.carlos@hotmail.com', 22);
CALL PR3('laura.sosa@gmail.com', 24);
CALL PR3('miguel.angel@yahoo.com', 27);
CALL PR3('valentina.moreno@gmail.com', 28);
CALL PR3('ricardo.ortiz@hotmail.com', 26);
CALL PR3('paola.lopez@yahoo.com', 30);
CALL PR3('diego.jimenez@gmail.com', 29);
CALL PR3('camila.rojas@hotmail.com', 31);
CALL PR3('oscar.ruiz@yahoo.com', 23);
CALL PR3('patricia.cruz@gmail.com', 32);
CALL PR3('felipe.castro@hotmail.com', 33);
CALL PR3('daniel.vega@gmail.com', 34);
CALL PR3('karina.mendoza@yahoo.com', 35);
CALL PR3('rodrigo.perez@hotmail.com', 36);

-- Cambio rol
CALL PR2('florencia.ortiz@gmail.com', 1);
CALL PR2('gustavo.ramirez@yahoo.com', 0);
CALL PR2('adriana.diaz@hotmail.com', 1);
CALL PR2('mauricio.martinez@gmail.com', 0);
CALL PR2('jessica.vargas@yahoo.com', 1);
CALL PR2('hector.reyes@hotmail.com', 0);
CALL PR2('karina.mendoza@yahoo.com', 1);

-- Validacion Datos
CALL PR6();
