version: '3.8'

services:
  sqlserver:
    build: .
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backups:/var/opt/mssql/backups
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge