version: '3.8'

services:
  sqlserver:
    build: .
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Practica1@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./app:/var/opt/mssql/app
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge